---
- name: 1. Add jonathonf PPA
  apt_repository:
    repo: deb http://ppa.launchpad.net/jonathonf/python-3.6/ubuntu xenial main
    state: present
  become: yes
  become_method: sudo

- name: 2. Ensure python 3.6 is installed
  apt:
    name: python3.6
    state: present
    update_cache: yes
    allow_unauthenticated: yes
  become: yes
  become_method: sudo

- name: 3. Ensure pip3 is installed
  apt:
    name: python3-pip
    state: latest
  become: yes
  become_method: sudo

- name: 4. Install 'virtualenv' package
  pip:
    name: virtualenv
    state: latest
    executable: pip3
  become: yes
  become_method: sudo

- name: 5. Create virtualenv
  pip:
    virtualenv: "{{ project_env }}"
    virtualenv_python: python3.6
    requirements: "{{ project }}/requirements/base.txt"
  become: yes
  become_method: sudo

- name: 6. Ensure Django is present in the virtualenv
  pip:
    name: Django
    state: latest
    virtualenv: "{{ project_env }}"
  become: yes
  become_method: sudo

- stat: path={{ project }}/manage.py
  register: manage

- stat: path={{ project }}/requirements/base.txt
  register: project_requirements

- name: 7. Ensure that a Django project exists
  shell: . {{ project_env }}/bin/activate && django-admin.py startproject app . chdir={{ project }}
  when: manage.stat.exists is not defined or manage.stat.exists == False

- name: 8. Apply project schema to database engine
  shell: . {{ project_env }}/bin/activate && python manage.py migrate chdir={{ project }}

- name: 9. Ensure STATIC_URL points to server assets correctly
  script: set_settings_variable.sh -d {{ project }}/app -k "STATIC_URL" -v "'\/static\/'"

- name: 10. Ensure STATIC_ROOT is set in project settings
  script: set_settings_variable.sh -d {{ project }}/app -k "STATIC_ROOT" -v "os.path.join(BASE_DIR, 'static')"

- name: 11. Django - collectstatic
  shell: . {{ project_env }}/bin/activate && python manage.py collectstatic --noinput chdir={{ project }}