---
- hosts: all
  remote_user: vagrant
  vars_files:
    - settings.yml
  roles:
    - apache
    - django
  post_tasks:
    - name: Update and upgrade apt packages
      apt:
        upgrade: yes
        update_cache: yes
        cache_valid_time: 86400
        allow_unauthenticated: yes
      become: true
      become_method: sudo

    - name: Provisioning has completed!
      shell: "true"
      notify:
        - Restart Apache